services:
  db:
    build:
      context: .
      dockerfile: DockerfileSQL
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tallerwebi
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","-u","root","-proot"]
      timeout: 20s
      retries: 10
 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      
  app:
    build:
      context: .
      dockerfile: DockerfileJetty
    container_name: jetty-app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: tallerwebi
      DB_USER: root
      DB_PASSWORD: root


volumes:
  db_data:

